exclude: ^(prompts|scripts|docs|images)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [--line-length, "120"]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--ignore=E501"]
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.10'
    hooks:
    - id: bandit
      args: [--severity-level, high, --confidence-level, all]
