# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^prompts/
      - id: end-of-file-fixer
        exclude: ^prompts/
      - id: check-yaml
        exclude: ^prompts/
      - id: check-added-large-files
        exclude: ^prompts/
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        exclude: ^prompts/
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--ignore=E501"]
        exclude: ^(prompts|scripts)
