name: Update Fabric Patterns

on:
  workflow_dispatch: {}
  # Schedule the CI job (this method uses cron syntax):
  schedule:
    - cron: '0 18 * * 5'  # Runs at 18:00 UTC every Friday

jobs:
  update_fabric_patterns:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Get changed files
        id: changed_files
        run: |
          bash scripts/download_fabric_patterns.sh

          git add prompts/fabric_patterns/
          CHANGED_FILES_RAW=$(git status --porcelain prompts/fabric_patterns/)
          CHANGED_FILES=$(git status --porcelain prompts/fabric_patterns/ | grep "^[AM]" | awk '{print $2}')
          echo "$CHANGED_FILES_RAW"
          if [ -z "$CHANGED_FILES_RAW" ]; then
            echo "No fabric patterns changes"
            exit 0
          fi
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "changed_files_raw<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES_RAW" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Process changed patterns
        id: python_code
        run: |
          export CHANGED_FILES="${{ steps.changed_files.outputs.changed_files }}"
          poetry run python scripts/generate_fabric_tools.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Prepare input
        id: prepare_input
        run: |
          printf "Modified files:\n" > pr.md
          printf '\n```\n${{ steps.changed_files.outputs.changed_files_raw }}\n```\n' >> pr.md
          printf "Python code to add:\n" >> pr.md
          printf '\n```' >> pr.md
          cat fabric_tools.txt >> pr.md
          printf '\n```\n' >> pr.md

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: fabric patterns"
          branch: patterns/cron-update
          delete-branch: true
          title: "Update fabric patterns"
          body-path: pr.md
          add-paths: |
            prompts/fabric_patterns/**
          labels: |
            fabric
            patterns
